### PR TITLE
Adds response verification, test id, and

### PR DESCRIPTION
**Pull request by bgy36ww**
checcks key press only for key listed

Update parameter launch test to use something that's not a video

### CODE REVIEW

**Review by akshaygarg86 — APPROVED** [review]
Looking good. 2 requests:

1. Change all file names to camelCase or snake_case to keep things consistent.
2. Update sample_result.json with the latest format.

Ok for you to merge after that.

Thx!!

**Review by akshaygarg86 — COMMENTED** [review]
Were you planning to update sample_result.json as well?

**Review by akshaygarg86 — APPROVED** [review]

**Review by akshaygarg86 — COMMENTED** [review]
@bgy36ww Should we also add the ability to execute a test case by its test_id and not an index from the list?

**Comment by bgy36ww** [comment]
Yay, can you file an issue so I don't lose it?

**Pull request merged**
